// Runs inside the empty consumer project, under plain Node: checks what the bundled entry made of each package, and
// runs the two bins pnpm linked into the project.
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

import { baseCss, contact, css, html, knowsMantine, pagesFromSitemap, serve, title } from "./consumer-bundle.mjs";

// theme
assert.match(css, /^\/\* Generated by @coralreefventures\/theme; do not edit\. \*\/\n:root\{/);
assert.match(css, /--mantine-color-ground-8: #102030;/);
assert.match(css, /--mantine-font-family: var\(--consumer-font, /);
console.log("theme: ok");

// contact
const event = (body) => ({ requestContext: { http: { method: "POST" } }, body: JSON.stringify(body) });
assert.equal((await contact(event({ name: "A", email: "x" }))).statusCode, 400);
assert.equal((await contact(event({ name: "A", email: "a@b.co", website: "spam" }))).statusCode, 200);
console.log("contact: ok");

// site-tools: the library, and the two bins
mkdirSync("out", { recursive: true });
writeFileSync("out/index.html", "<h1>Home</h1>");
writeFileSync("out/404.html", "<h1>Page not found.</h1>");
writeFileSync("out/sitemap.xml", "<urlset><url><loc>https://consumer.example/</loc></url></urlset>");
assert.deepEqual(await pagesFromSitemap("out"), ["/"]);
const { server, url } = await serve({ root: "out", port: 0 });
assert.equal((await fetch(`${url}/`)).status, 200);
assert.equal((await fetch(`${url}/nope/`)).status, 404);
server.close();
for (const bin of ["reef-serve", "reef-lighthouse"]) {
  const help = execFileSync("pnpm", ["exec", bin, "--help"], { encoding: "utf8" });
  assert.match(help, new RegExp(`^${bin} `), `${bin} prints its usage`);
}
console.log("site-tools: ok");

// site
assert.match(html, /<a href="#main" class="skip-link">Skip to content<\/a><header/);
assert.match(html, /aria-current="page">Product<\/a>/);
assert.match(html, /Jira are trademarks of their owners; Consumer is not affiliated with them/);
assert.match(html, /class="[^"]*display[^"]*">Hello</);
assert.match(html, /data-tone="attention">Later</);
assert.equal(title, "Product");
assert.ok(existsSync(fileURLToPath(baseCss)), "base.css is reachable through the package's exports");
assert.equal(knowsMantine, true);
console.log("site: ok");
