// Runs inside the empty consumer project, under plain Node: checks what the bundled entry made of each package, and
// runs the two bins pnpm linked into the project.
import assert from "node:assert/strict";
import { execFileSync, spawn } from "node:child_process";
import { generateKeyPairSync, randomUUID, sign } from "node:crypto";
import { cpSync, existsSync, mkdirSync, mkdtempSync, rmSync, writeFileSync } from "node:fs";
import { request } from "node:http";
import { createServer } from "node:net";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

import {
  baseCss,
  canonicalNext,
  contact,
  css,
  html,
  knowsMantine,
  pagesFromSitemap,
  serve,
  title,
} from "./consumer-bundle.mjs";

// theme
assert.match(css, /^\/\* Generated by @coralreefventures\/theme; do not edit\. \*\/\n:root\{/);
assert.match(css, /--mantine-color-ground-8: #102030;/);
assert.match(css, /--mantine-font-family: var\(--consumer-font, /);
console.log("theme: ok");

// contact
const event = (body) => ({ requestContext: { http: { method: "POST" } }, body: JSON.stringify(body) });
assert.equal((await contact(event({ name: "A", email: "x" }))).statusCode, 400);
assert.equal((await contact(event({ name: "A", email: "a@b.co", website: "spam" }))).statusCode, 200);
console.log("contact: ok");

// site-tools: the library, and the two bins
mkdirSync("out", { recursive: true });
writeFileSync("out/index.html", "<h1>Home</h1>");
writeFileSync("out/404.html", "<h1>Page not found.</h1>");
writeFileSync("out/sitemap.xml", "<urlset><url><loc>https://consumer.example/</loc></url></urlset>");
assert.deepEqual(await pagesFromSitemap("out"), ["/"]);
const { server, url } = await serve({ root: "out", port: 0 });
assert.equal((await fetch(`${url}/`)).status, 200);
assert.equal((await fetch(`${url}/nope/`)).status, 404);
server.close();
for (const bin of ["reef-serve", "reef-lighthouse", "reef-door-bundle"]) {
  const help = execFileSync("pnpm", ["exec", bin, "--help"], { encoding: "utf8" });
  assert.match(help, new RegExp(`^${bin} `), `${bin} prints its usage`);
}
console.log("site-tools: ok");

// site-tools: the door gate. The bin locks the export, and the bundle it writes runs on its own, moved away from any
// node_modules, which is how Amplify runs it.
assert.equal(canonicalNext("/\\evil.com", "consumer.example"), null);
const { publicKey, privateKey } = generateKeyPairSync("ec", { namedCurve: "P-256" });
writeFileSync("jwks.json", JSON.stringify({ keys: [{ ...publicKey.export({ format: "jwk" }), kid: "smoke" }] }));
const gatePort = await new Promise((resolve) => {
  const probe = createServer().listen(0, "127.0.0.1", () => {
    const { port } = probe.address();
    probe.close(() => resolve(port));
  });
});
const gateHost = `localhost:${gatePort}`;
execFileSync("pnpm", [
  "exec",
  "reef-door-bundle",
  "--site",
  "consumer",
  "--door-url",
  "https://door.example",
  "--hosts",
  gateHost,
  "--jwks-url",
  pathToFileURL("jwks.json").href,
  "--name",
  "Consumer Site",
  "--accent",
  "#2a5a8c",
]);
const compute = mkdtempSync(join(tmpdir(), "reef-gate-"));
cpSync(".amplify-hosting/compute/default", compute, { recursive: true });
const gate = spawn(process.execPath, [join(compute, "server.mjs")], {
  env: { PATH: process.env.PATH, PORT: String(gatePort) },
  stdio: "ignore",
});
try {
  // node:http rather than fetch, which will not send a Host header of its own choosing.
  const get = (path, headers = {}) =>
    new Promise((resolve, reject) => {
      const req = request(
        { host: "127.0.0.1", port: gatePort, path, headers: { host: gateHost, ...headers } },
        (res) => {
          let text = "";
          res.on("data", (chunk) => {
            text += chunk;
          });
          res.on("end", () => resolve({ status: res.statusCode, headers: res.headers, text }));
        },
      );
      req.on("error", reject);
      req.end();
    });
  for (let attempt = 0; ; attempt++) {
    const health = await get("/_door/health").catch(() => undefined);
    if (health?.status === 200) break;
    assert.ok(attempt < 100, "the gate starts");
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  const noSession = await get("/");
  assert.equal(noSession.status, 401);
  assert.equal(noSession.text, "");
  // A page load without a session gets the coming-soon page, whose button starts a sign-in at the door.
  const comingSoon = await get("/docs/", { "sec-fetch-mode": "navigate", accept: "text/html" });
  assert.equal(comingSoon.status, 401);
  assert.match(comingSoon.text, /<h1>Consumer Site is coming soon\.<\/h1>/);
  assert.match(comingSoon.text, /href="\/_door\/signin\?next=%2Fdocs%2F"/);
  assert.match(comingSoon.headers["content-security-policy"], /^default-src 'none'/);
  // Only a page load starts a sign-in; anything else sets no state cookie.
  const fetched = await get("/_door/signin?next=%2Fdocs%2F", {
    "sec-fetch-mode": "no-cors",
    "sec-fetch-dest": "image",
  });
  assert.equal(fetched.status, 401);
  assert.equal(fetched.headers["set-cookie"], undefined);
  const signin = await get("/_door/signin?next=%2Fdocs%2F", { "sec-fetch-mode": "navigate", accept: "text/html" });
  assert.equal(signin.status, 302);
  assert.equal(new URL(signin.headers.location).searchParams.get("next"), "/docs/");
  assert.match(signin.headers["set-cookie"]?.[0] ?? "", /^__Host-crv_door_state=/);
  const encode = (value) => Buffer.from(JSON.stringify(value)).toString("base64url");
  const iat = Math.floor(Date.now() / 1000);
  const head = encode({ alg: "ES256", kid: "smoke" });
  const body = encode({
    iss: "https://door.example",
    aud: gateHost,
    sub: "p",
    gid: "g",
    jti: randomUUID(),
    iat,
    exp: iat + 600,
  });
  const signature = sign("sha256", Buffer.from(`${head}.${body}`), { key: privateKey, dsaEncoding: "ieee-p1363" });
  const session = await get("/", { cookie: `__Host-crv_door=${head}.${body}.${signature.toString("base64url")}` });
  assert.equal(session.status, 200);
  assert.equal(session.text, "<h1>Home</h1>");
  assert.equal(session.headers["cache-control"], "private, no-store");
  assert.match((await get("/robots.txt")).text, /Disallow: \//);
} finally {
  gate.kill();
  rmSync(compute, { recursive: true, force: true });
}
console.log("site-tools door: ok");

// site
assert.match(html, /<a href="#main" class="skip-link">Skip to content<\/a><header/);
assert.match(html, /aria-current="page">Product<\/a>/);
assert.match(html, /Jira are trademarks of their owners; Consumer is not affiliated with them/);
assert.match(html, /class="[^"]*display[^"]*">Hello</);
assert.match(html, /data-tone="attention">Later</);
assert.equal(title, "Product");
assert.ok(existsSync(fileURLToPath(baseCss)), "base.css is reachable through the package's exports");
assert.equal(knowsMantine, true);
console.log("site: ok");
