import { readFile } from "node:fs/promises";

import { DEFAULT_THEME } from "@mantine/core";
import { describe, expect, it } from "vitest";

import { brandColor, brandFontFamily, createBrandTheme, themeCss } from "../src/index";
import { driftlineConfig, driftlineTokens } from "./fixtures/driftline/theme";
import { streamlaneResolver } from "./fixtures/streamlane/resolver";
import { streamlaneConfig, streamlaneTokens } from "./fixtures/streamlane/theme";

const fixture = (name: string) => readFile(new URL(`./fixtures/${name}/theme.css`, import.meta.url), "utf8");

/**
 * The contract that lets each product replace its theme builder with this one: run over the product's own tokens
 * and choices, the stylesheet comes out byte for byte as the product generates it today.
 */
describe("the generated stylesheet", () => {
  it("is byte-identical to Streamlane's committed theme.css", async () => {
    const theme = createBrandTheme(streamlaneTokens, streamlaneConfig);
    const css = themeCss(theme, {
      generatedBy: "packages/theme (pnpm --filter @streamlane/theme generate)",
      resolver: streamlaneResolver,
    });
    expect(css).toBe(await fixture("streamlane"));
  });

  it("is byte-identical to Driftline's committed theme.css", async () => {
    const theme = createBrandTheme(driftlineTokens, driftlineConfig);
    const css = themeCss(theme, { generatedBy: "packages/theme (pnpm --filter @driftline/theme generate)" });
    expect(css).toBe(await fixture("driftline"));
  });

  it("names this package when nothing else is named", () => {
    expect(themeCss(createBrandTheme(driftlineTokens, driftlineConfig))).toMatch(
      /^\/\* Generated by @coralreefventures\/theme; do not edit\. \*\/\n:root/,
    );
  });
});

describe("createBrandTheme", () => {
  const theme = createBrandTheme(streamlaneTokens, streamlaneConfig);

  it("puts the brand colors at their fixed points in the scales", () => {
    expect(theme.colors?.ink?.[8]).toBe("#123A3C");
    expect(theme.colors?.ink?.[7]).toBe("#1E4C4E");
    expect(theme.colors?.signal?.[5]).toBe("#F2A93B");
    expect(theme.colors?.signal?.[3]).toBe("#F6C575");
  });

  it("puts the font behind the app's variable, over Mantine's own stack", () => {
    expect(theme.fontFamily).toBe(`var(--streamlane-font-sans, ${DEFAULT_THEME.fontFamily})`);
    expect(theme.headings?.fontFamily).toBe(theme.fontFamily);
    expect(theme.headings?.fontWeight).toBe("700");
    expect(brandFontFamily("--x")).toBe(`var(--x, ${DEFAULT_THEME.fontFamily})`);
  });

  it("takes black from the brand when asked, and leaves it to Mantine otherwise", () => {
    expect(theme.black).toBe("#152526");
    expect(createBrandTheme(driftlineTokens, driftlineConfig).black).toBeUndefined();
  });

  it("refuses a color name the brand does not have, and a primary color that is not a scale", () => {
    expect(() => brandColor(driftlineTokens, "signal")).toThrow(/no color named "signal"/);
    expect(() => createBrandTheme(driftlineTokens, { ...driftlineConfig, primaryColor: "ink" })).toThrow(
      /"ink" is not one of the theme's scales/,
    );
  });
});
