import { writeFile } from "node:fs/promises";

import {
  type CSSVariablesResolver,
  convertCssVariables,
  DEFAULT_THEME,
  defaultCssVariablesResolver,
  type MantineThemeOverride,
  mergeMantineTheme,
} from "@mantine/core";

export type ThemeCssOptions = {
  /**
   * Named in the stylesheet's first line so a reader knows what to run instead of editing it, such as
   * `packages/theme (pnpm --filter <product>/theme generate)`; this package's name when nothing is given.
   */
  generatedBy?: string;
  /**
   * The theme's own CSS variables and its corrections to Mantine's, per scheme, merged as MantineProvider merges a
   * resolver it is given: the theme's variables over Mantine's own.
   */
  resolver?: CSSVariablesResolver;
};

/**
 * The CSS variables MantineProvider would inject for a theme, as a stylesheet. A page that renders without the
 * provider (a server component with no client code under it) still gets the theme's colors, type, spacing and radii,
 * and a page that renders with it loads nothing twice (`withCssVariables={false}`).
 */
export const themeCss = (theme: MantineThemeOverride, options: ThemeCssOptions = {}): string => {
  const merged = mergeMantineTheme(DEFAULT_THEME, theme);
  const base = defaultCssVariablesResolver(merged);
  const own = options.resolver?.(merged) ?? { variables: {}, light: {}, dark: {} };
  const css = convertCssVariables(
    {
      variables: { ...base.variables, ...own.variables },
      light: { ...base.light, ...own.light },
      dark: { ...base.dark, ...own.dark },
    },
    ":root",
  );
  const generatedBy = options.generatedBy ?? "@coralreefventures/theme";
  return `/* Generated by ${generatedBy}; do not edit. */\n${css.trim()}\n`;
};

/**
 * Writes the stylesheet, for a product's `generate` script; its test compares the committed file with `themeCss()`
 * and fails when the two differ, which is how a stale file is caught.
 */
export const writeThemeCss = async (file: URL | string, css: string): Promise<void> => {
  await writeFile(file, css);
};
